# Generated by Django 5.2.4 on 2025-08-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='softwarekit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('software_info', models.TextField(null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static/softwarethumb/')),
                ('download_link', models.CharField(max_length=200, null=True)),
                ('posted_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/category/')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.batch')),
            ],
        ),
        migrations.CreateModel(
            name='tblregister',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, upload_to='static/userpic/')),
                ('address', models.TextField(null=True)),
                ('regdate', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.batch')),
            ],
        ),
    ]
